### ISSUE TITLE
detach() vs detachall()

### ISSUE THREAD

**Issue by getgray** [dadul96/Arduino-Servo-Hardware-PWM-Library#5]
If no pin number is required for detach() (per docs), how do you reference which servo to detach? And then, what is the difference between:

detach() — Clears the used registers and stops the output of the attached pin. (no pin number!)
detachAll() — Clears the used registers and stops the output of ALL attached pins. (no pin number!)

**Comment by dadul96** [comment]
When attaching a certain pin, the pin number is stored as a class member. The detach() method uses this class member to specify which pin/timer to detach. That's also the reason why you don't need to specify a pin number when setting a certain angle via the write() method.

The detachAll() method, on the other hand, detaches all previously attached pins/timers of any Servo-class instance. My idea was to provide a simple way to detach all servos across all Servo-class instances using only one method from one instance. I have implemented an array (of global scope) inside the *.cpp file to store which pins are attached across all existing Servo-class instances.

**Comment by getgray** [comment]
Thank you.
